"""second

Revision ID: 92778b7fac77
Revises: d46fe6c52a91
Create Date: 2023-03-26 10:55:44.415113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92778b7fac77'
down_revision = 'd46fe6c52a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    with op.batch_alter_table('Urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Urls', schema=None) as batch_op:
        batch_op.drop_column('full_url')

    op.create_table('url',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('short_url', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###
